import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute } from '@react-navigation/native';
import { useESignConsent } from '../hooks/useESignConsent';

const COLORS = {
  background: '#0F172A',
  card: '#1E293B',
  surface: '#243047',
  text: '#F1F5F9',
  textSecondary: '#64748B',
  border: '#374151',
  purple: '#7C3AED',
  success: '#059669',
  danger: '#DC2626',
};

const CONSENT_TEXT =
  'By checking this box, I agree to use electronic signatures for dispute letters and other ' +
  'documents generated by Credit Stamina. I understand that my electronic signature is legally ' +
  'binding and has the same legal effect as a handwritten signature under the Electronic ' +
  'Signatures in Global and National Commerce Act (ESIGN) and the Uniform Electronic Transactions ' +
  'Act (UETA). I can withdraw this consent at any time by contacting support@creditstamina.com.';

const ESignConsentScreen = () => {
  const navigation = useNavigation();
  const route = useRoute();
  const { letterData } = route.params ?? {};

  const { giveConsent } = useESignConsent();
  const [checked, setChecked] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleConsent = async () => {
    if (!checked) return;
    setSaving(true);
    try {
      await giveConsent();
      // After consent, proceed directly to the signature screen
      navigation.replace('Signature', { letterData });
    } catch (err) {
      Alert.alert(
        'Error',
        err?.message || 'Could not record your consent. Please try again.'
      );
    } finally {
      setSaving(false);
    }
  };

  const handleDecline = () => {
    navigation.goBack();
  };

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          onPress={handleDecline}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <Text style={styles.cancelBtn}>Cancel</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Electronic Signature Consent</Text>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        {/* Shield icon + intro */}
        <View style={styles.iconBlock}>
          <Text style={styles.shieldIcon}>🔒</Text>
          <Text style={styles.introTitle}>One-Time Consent Required</Text>
          <Text style={styles.introText}>
            Before you can sign documents in Credit Stamina, we need your consent to use
            electronic signatures. This is a one-time step — you will not see this screen again.
          </Text>
        </View>

        {/* Legal framework badges */}
        <View style={styles.badgeRow}>
          {['ESIGN Act', 'UETA', 'Legally Binding'].map(label => (
            <View key={label} style={styles.badge}>
              <Text style={styles.badgeText}>{label}</Text>
            </View>
          ))}
        </View>

        {/* Consent text box */}
        <View style={styles.consentBox}>
          <Text style={styles.consentBoxLabel}>CONSENT DISCLOSURE</Text>
          <Text style={styles.consentBoxText}>{CONSENT_TEXT}</Text>
        </View>

        {/* What this means section */}
        <View style={styles.infoCard}>
          <Text style={styles.infoCardTitle}>What this means</Text>
          {[
            'Your drawn signature has the same legal effect as a handwritten signature.',
            'Your consent date and timestamp are securely recorded in our system.',
            'You can withdraw consent at any time by emailing support@creditstamina.com.',
            'Credit Stamina retains an audit trail of all signed documents.',
          ].map((item, i) => (
            <View key={i} style={styles.infoItem}>
              <Text style={styles.infoItemDot}>✓</Text>
              <Text style={styles.infoItemText}>{item}</Text>
            </View>
          ))}
        </View>

        {/* Consent checkbox */}
        <TouchableOpacity
          style={styles.checkRow}
          onPress={() => setChecked(v => !v)}
          activeOpacity={0.7}
        >
          <View style={[styles.checkbox, checked && styles.checkboxChecked]}>
            {checked && <Text style={styles.checkmark}>✓</Text>}
          </View>
          <Text style={styles.checkLabel}>
            I consent to use electronic signatures
          </Text>
        </TouchableOpacity>

        {/* Continue to Sign button */}
        <TouchableOpacity
          style={[styles.continueBtn, !checked && styles.continueBtnDisabled]}
          onPress={handleConsent}
          disabled={!checked || saving}
          activeOpacity={0.85}
        >
          {saving
            ? <ActivityIndicator color="#fff" size="small" />
            : <Text style={styles.continueBtnText}>Continue to Sign</Text>
          }
        </TouchableOpacity>

        {/* Decline */}
        <TouchableOpacity style={styles.declineBtn} onPress={handleDecline} activeOpacity={0.7}>
          <Text style={styles.declineBtnText}>Decline — Go Back</Text>
        </TouchableOpacity>

        <Text style={styles.footerNote}>
          Your consent is stored securely and linked to your account. To review or withdraw consent
          at any time, visit Settings → Privacy &amp; Legal.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  cancelBtn: { fontSize: 16, color: COLORS.textSecondary, fontWeight: '500', minWidth: 60 },
  title: { fontSize: 17, fontWeight: '700', color: COLORS.text },
  headerSpacer: { minWidth: 60 },

  content: { padding: 20, paddingBottom: 40 },

  iconBlock: { alignItems: 'center', marginBottom: 20 },
  shieldIcon: { fontSize: 48, marginBottom: 12 },
  introTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text, marginBottom: 8, textAlign: 'center' },
  introText: { fontSize: 14, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 20 },

  badgeRow: { flexDirection: 'row', justifyContent: 'center', gap: 8, marginBottom: 20, flexWrap: 'wrap' },
  badge: {
    backgroundColor: COLORS.purple + '20',
    borderWidth: 1,
    borderColor: COLORS.purple + '50',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  badgeText: { fontSize: 12, color: COLORS.purple, fontWeight: '600' },

  consentBox: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginBottom: 16,
  },
  consentBoxLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 1,
    marginBottom: 10,
  },
  consentBoxText: { fontSize: 13, color: COLORS.text, lineHeight: 21 },

  infoCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  infoCardTitle: { fontSize: 13, fontWeight: '700', color: COLORS.text, marginBottom: 10 },
  infoItem: { flexDirection: 'row', gap: 8, marginBottom: 7 },
  infoItemDot: { color: COLORS.success, fontWeight: '700', fontSize: 14, marginTop: 1 },
  infoItemText: { flex: 1, fontSize: 13, color: COLORS.textSecondary, lineHeight: 19 },

  checkRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 20,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    marginTop: 1,
  },
  checkboxChecked: { backgroundColor: COLORS.purple, borderColor: COLORS.purple },
  checkmark: { color: '#fff', fontSize: 14, fontWeight: '800' },
  checkLabel: { flex: 1, fontSize: 14, color: COLORS.text, lineHeight: 21, fontWeight: '500' },

  continueBtn: {
    backgroundColor: COLORS.purple,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  continueBtnDisabled: { backgroundColor: '#374151', opacity: 0.55 },
  continueBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },

  declineBtn: {
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  declineBtnText: { fontSize: 14, color: COLORS.textSecondary, fontWeight: '500' },

  footerNote: {
    fontSize: 11,
    color: COLORS.textSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 16,
  },
});

export default ESignConsentScreen;
